
--- #local
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  datasource:
    url: jdbc:mysql://localhost:3306/mwo?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.sptial.dialect.mysql.MySQL56InnoDBSpatialDialect
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: ture
  config:
    activate:
      on-profile: local
---


